plugins:
  - '@dotcom-tool-kit/circleci-npm'
  - '@dotcom-tool-kit/husky-npm'
  - '@dotcom-tool-kit/eslint'
hooks:
  git:precommit:
    - Eslint
options:
  '@dotcom-tool-kit/eslint':
    files:
      - '**/*.js'
  '@dotcom-tool-kit/circleci':
    nodeVersion:
      - '18.16'
      - '16.20'
