# AWS keys
auth:
  # An access key with permissions to read and write to the Elasticsearch service
  access_key: {{AWS_ACCESS_KEY}}
  # The secret key to match the access key above
  secret_key: {{AWS_SECRET_ACCESS_KEY}}

# Paths to the Elasticsearch clusters to be managed
clusters:
  eu: {{ELASTIC_SEARCH_HOST_EU}}
  us: {{ELASTIC_SEARCH_HOST_US}}
  dev: {{ELASTIC_SEARCH_HOST_DEV}}

# API keys
keys:
  # Key for the FT content API (V1 and V2)
  capi: {{API_KEY}}
